CREATE SCHEMA tbot;

CREATE TABLE tbot.category (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  info text,
  parent_id integer,
  CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE tbot.user (
  chat_id integer NOT NULL,
  first_name text,
  last_name text,
  is_admin boolean,
  state text,
  CONSTRAINT pk_user PRIMARY KEY (chat_id)
);

CREATE TABLE tbot.visits (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  category_id integer NOT NULL,
  chat_id integer NOT NULL,
  visit_date date NOT NULL,
  CONSTRAINT pk_visits PRIMARY KEY (id)
);

ALTER TABLE tbot.visits ADD CONSTRAINT fk_tbot_category_id FOREIGN KEY (category_id) REFERENCES tbot.category (id) ON DELETE CASCADE;
ALTER TABLE tbot.visits ADD CONSTRAINT fk_tbot_chat_id FOREIGN KEY (chat_id) REFERENCES tbot.user (chat_id) ON DELETE CASCADE;